def city_codes():
    return [{
    'ABV': 'Abuja',
    'ACC': 'Accra',
    'ADD': 'Addis Ababa',
    'ALG': 'Algiers',
    'AMM': 'Amman',
    'AMS': 'Amsterdam',
    'ESB': 'Ankara',
    'FGI': 'Apia',
    'ASB': 'Ashgabat',
    'ASM': 'Asmara',
    'TSE': 'Astana',
    'ASU': 'Asuncion',
    'ATH': 'Athens',
    'BGW': 'Baghdad',
    'GYD': 'Baku',
    'BKO': 'Bamako',
    'BKK': 'Bangkok',
    'BGF': 'Bangui',
    'BJL': 'Banjul',
    'SKB': 'Basseterre',
    'PEK': 'Beijing',
    'BEY': 'Beirut',
    'BEG': 'Belgrade',
    'BZE': 'Belmopan',
    'BER': 'Berlin',
    'BRN': 'Bern',
    'FRU': 'Bishkek',
    'OXB': 'Bissau',
    'BOG': 'Bogota',
    'BSB': 'Brasilia',
    'BTS': 'Bratislava',
    'BZV': 'Brazzaville',
    'BGI': 'Bridgetown',
    'BRU': 'Brussels',
    'OTP': 'Bucharest',
    'BUD': 'Budapest',
    'EZE': 'Buenos Aires',
    'BJM': 'Bujumbura',
    'CAI': 'Cairo',
    'CBR': 'Canberra',
    'CCS': 'Caracas',
    'CWL': 'Cardiff',
    'SLU': 'Castries',
    'CAY': 'Cayenne',
    'KIV': 'Chisinau',
    'CKY': 'Conakry',
    'CPH': 'Copenhagen',
    'DKR': 'Dakar',
    'DAM': 'Damascus',
    'DAC': 'Dhaka',
    'DIL': 'Dili',
    'JIB': 'Djibouti',
    'DAR': 'Dodoma',
    'DOH': 'Doha',
    'IOM': 'Douglas',
    'DUB': 'Dublin',
    'DYU': 'Dushanbe',
    'EDI': 'Edinburgh',
    'FNA': 'Freetown',
    'FUN': 'Funafuti',
    'GBE': 'Gaborone',
    'GCM': 'George Town',
    'GEO': 'Georgetown',
    'GIB': 'Gibraltar',
    'GUM': 'Hagatna',
    'HAN': 'Hanoi',
    'HRE': 'Harare',
    'HAV': 'Havana',
    'HEL': 'Helsinki',
    'HIR': 'Honiara',
    'ISB': 'Islamabad',
    'CGK': 'Jakarta',
    'JRS': 'Jerusalem',
    'JUB': 'Juba',
    'KBL': 'Kabul',
    'EBB': 'Kampala',
    'KTM': 'Kathmandu',
    'KRT': 'Khartoum',
    'IEV': 'Kiev',
    'KGL': 'Kigali',
    'KIN': 'Kingston',
    'SVD': 'Kingstown',
    'FIH': 'Kinshasa',
    'KUL': 'Kuala Lumpur',
    'KWI': 'Kuwait City',
    'LPB': 'La Paz',
    'LBV': 'Libreville',
    'LLW': 'Lilongwe',
    'LIM': 'Lima',
    'LIS': 'Lisbon',
    'LJU': 'Ljubljana',
    'LFW': 'Lome',
    'LHR': 'London',
    'LUN': 'Lusaka',
    'LUX': 'Luxembourg City',
    'MAD': 'Madrid',
    'MAJ': 'Majuro',
    'SSG': 'Malabo',
    'MLE': 'Malé',
    'MGA': 'Managua',
    'BAH': 'Manama',
    'MNL': 'Manila',
    'MPM': 'Maputo',
    'MSU': 'Maseru',
    'SHO': 'Mbabane',
    'ROR': 'Melekeok',
    'MEX': 'Mexico City',
    'MSQ': 'Minsk',
    'MGQ': 'Mogadishu',
    'MCM': 'Monaco',
    'ROB': 'Monrovia',
    'MVD': 'Montevideo',
    'HAH': 'Moroni',
    'SVO': 'Moscow',
    'MCT': 'Muscat',
    'NBO': 'Nairobi',
    'NAS': 'Nassau',
    'NYP': 'Naypyidaw',
    'DEL': 'New Delhi',
    'NIC': 'Nicosia',
    'NKC': 'Nouakchott',
    'TBU': 'Nuku\'alofa',
    'GOH': 'Nuuk',
    'AUA': 'Oranjestad',
    'OSL': 'Oslo',
    'YOW': 'Ottawa',
    'OUA': 'Ouagadougou',
    'PNI': 'Palikir',
    'PTY': 'Panama City',
    'PBM': 'Paramaribo',
    'PAR': 'Paris',
    'SXM': 'Philipsburg',
    'PNH': 'Phnom Penh',
    'TGD': 'Podgorica',
    'MRU': 'Port Louis',
    'POM': 'Port Moresby',
    'VLI': 'Port Vila',
    'PAP': 'Port-au-Prince',
    'POS': 'Port of Spain',
    'RAI': 'Praia',
    'PRY': 'Pretoria',
    'FNJ': 'Pyongyang',
    'UIO': 'Quito',
    'RBA': 'Rabat',
    'ZDM': 'Ramallah',
    'KEF': 'Reykjavik',
    'RIX': 'Riga',
    'RUH': 'Riyadh',
    'FCO': 'Rome',
    'DCF': 'Roseau',
    'RUN': 'Saint-Denis',
    'ANU': 'Saint John\'s',
    'GCI': 'Saint Peter Port',
    'FSP': 'Saint-Pierre',
    'SPN': 'Saipan',
    'SJO': 'San Jose',
    'SJU': 'San Juan',
    'SAI': 'San Marino',
    'SAL': 'San Salvador',
    'SAH': 'Sana\'a',
    'SCL': 'Santiago',
    'SDQ': 'Santo Domingo',
    'TMS': 'Sao Tome',
    'SJJ': 'Sarajevo',
    'SEL': 'Seoul',
    'SIN': 'Singapore',
    'SKP': 'Skopje',
    'SOF': 'Sofia',
    'ARN': 'Stockholm',
    'SRE': 'Sucre',
    'SUV': 'Suva',
    'TPE': 'Taipei',
    'TLL': 'Tallinn',
    'TRW': 'Tarawa',
    'TAS': 'Tashkent',
    'TBS': 'Tbilisi',
    'TGU': 'Tegucigalpa',
    'IKA': 'Tehran',
    'PBH': 'Thimphu',
    'TIA': 'Tirana',
    'HND': 'Tokyo',
    'TIP': 'Tripoli',
    'TUN': 'Tunis',
    'ULN': 'Ulaanbaatar',
    'QKL': 'Vaduz',
    'MLA': 'Valletta',
    'VAT': 'Vatican City',
    'SEZ': 'Victoria',
    'VIE': 'Vienna',
    'VTE': 'Vientiane',
    'VNO': 'Vilnius',
    'WAW': 'Warsaw',
    'IAD': 'Washington D.C.',
    'WLG': 'Wellington',
    'WDH': 'Windhoek',
    'ASK': 'Yamoussoukro',
    'NSI': 'Yaounde',
    'EVN': 'Yerevan',
    'ZAG': 'Zagreb'
}
, 
{
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Congo, The Democratic Republic of The": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Cote D'ivoire": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Falkland Islands (Malvinas)": "FK",
    "Faroe Islands": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and Mcdonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran, Islamic Republic of": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea, Democratic People's Republic of": "KP",
    "Korea, Republic of": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libyan Arab Jamahiriya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Macedonia, The Former Yugoslav Republic of": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia, Federated States of": "FM",
    "Moldova, Republic of": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "Netherlands Antilles": "AN",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestinian Territory, Occupied": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Reunion": "RE",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saint Helena": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and The Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia and Montenegro": "CS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and The South Sandwich Islands": "GS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard and Jan Mayen": "SJ",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Taiwan, Province of China": "TW",
    "Tajikistan": "TJ",
    "Tanzania, United Republic of": "TZ",
    "Thailand": "TH",
    "Timor-leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Viet Nam": "VN",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.S.": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}]


