def city_codes():
    return [{
    'ABV': 'Abuja',
    'ACC': 'Accra',
    'ADD': 'Addis Ababa',
    'ALG': 'Algiers',
    'AMM': 'Amman',
    'AMS': 'Amsterdam',
    'ESB': 'Ankara',
    'FGI': 'Apia',
    'ASB': 'Ashgabat',
    'ASM': 'Asmara',
    'TSE': 'Astana',
    'ASU': 'Asuncion',
    'ATH': 'Athens',
    'BGW': 'Baghdad',
    'GYD': 'Baku',
    'BKO': 'Bamako',
    'BKK': 'Bangkok',
    'BGF': 'Bangui',
    'BJL': 'Banjul',
    'SKB': 'Basseterre',
    'PEK': 'Beijing',
    'BEY': 'Beirut',
    'BEG': 'Belgrade',
    'BZE': 'Belmopan',
    'BER': 'Berlin',
    'BRN': 'Bern',
    'FRU': 'Bishkek',
    'OXB': 'Bissau',
    'BOG': 'Bogota',
    'BSB': 'Brasilia',
    'BTS': 'Bratislava',
    'BZV': 'Brazzaville',
    'BGI': 'Bridgetown',
    'BRU': 'Brussels',
    'OTP': 'Bucharest',
    'BUD': 'Budapest',
    'EZE': 'Buenos Aires',
    'BJM': 'Bujumbura',
    'CAI': 'Cairo',
    'CBR': 'Canberra',
    'CCS': 'Caracas',
    'CWL': 'Cardiff',
    'SLU': 'Castries',
    'CAY': 'Cayenne',
    'KIV': 'Chisinau',
    'CKY': 'Conakry',
    'CPH': 'Copenhagen',
    'DKR': 'Dakar',
    'DAM': 'Damascus',
    'DAC': 'Dhaka',
    'DIL': 'Dili',
    'JIB': 'Djibouti',
    'DAR': 'Dodoma',
    'DOH': 'Doha',
    'IOM': 'Douglas',
    'DUB': 'Dublin',
    'DYU': 'Dushanbe',
    'EDI': 'Edinburgh',
    'FNA': 'Freetown',
    'FUN': 'Funafuti',
    'GBE': 'Gaborone',
    'GCM': 'George Town',
    'GEO': 'Georgetown',
    'GIB': 'Gibraltar',
    'GUM': 'Hagatna',
    'HAN': 'Hanoi',
    'HRE': 'Harare',
    'HAV': 'Havana',
    'HEL': 'Helsinki',
    'HIR': 'Honiara',
    'ISB': 'Islamabad',
    'CGK': 'Jakarta',
    'JRS': 'Jerusalem',
    'JUB': 'Juba',
    'KBL': 'Kabul',
    'EBB': 'Kampala',
    'KTM': 'Kathmandu',
    'KRT': 'Khartoum',
    'IEV': 'Kiev',
    'KGL': 'Kigali',
    'KIN': 'Kingston',
    'SVD': 'Kingstown',
    'FIH': 'Kinshasa',
    'KUL': 'Kuala Lumpur',
    'KWI': 'Kuwait City',
    'LPB': 'La Paz',
    'LBV': 'Libreville',
    'LLW': 'Lilongwe',
    'LIM': 'Lima',
    'LIS': 'Lisbon',
    'LJU': 'Ljubljana',
    'LFW': 'Lome',
    'LHR': 'London',
    'LUN': 'Lusaka',
    'LUX': 'Luxembourg City',
    'MAD': 'Madrid',
    'MAJ': 'Majuro',
    'SSG': 'Malabo',
    'MLE': 'Malé',
    'MGA': 'Managua',
    'BAH': 'Manama',
    'MNL': 'Manila',
    'MPM': 'Maputo',
    'MSU': 'Maseru',
    'SHO': 'Mbabane',
    'ROR': 'Melekeok',
    'MEX': 'Mexico City',
    'MSQ': 'Minsk',
    'MGQ': 'Mogadishu',
    'MCM': 'Monaco',
    'ROB': 'Monrovia',
    'MVD': 'Montevideo',
    'HAH': 'Moroni',
    'SVO': 'Moscow',
    'MCT': 'Muscat',
    'NBO': 'Nairobi',
    'NAS': 'Nassau',
    'NYP': 'Naypyidaw',
    'DEL': 'New Delhi',
    'NIC': 'Nicosia',
    'NKC': 'Nouakchott',
    'TBU': 'Nuku\'alofa',
    'GOH': 'Nuuk',
    'AUA': 'Oranjestad',
    'OSL': 'Oslo',
    'YOW': 'Ottawa',
    'OUA': 'Ouagadougou',
    'PNI': 'Palikir',
    'PTY': 'Panama City',
    'PBM': 'Paramaribo',
    'PAR': 'Paris',
    'SXM': 'Philipsburg',
    'PNH': 'Phnom Penh',
    'TGD': 'Podgorica',
    'MRU': 'Port Louis',
    'POM': 'Port Moresby',
    'VLI': 'Port Vila',
    'PAP': 'Port-au-Prince',
    'POS': 'Port of Spain',
    'RAI': 'Praia',
    'PRY': 'Pretoria',
    'FNJ': 'Pyongyang',
    'UIO': 'Quito',
    'RBA': 'Rabat',
    'ZDM': 'Ramallah',
    'KEF': 'Reykjavik',
    'RIX': 'Riga',
    'RUH': 'Riyadh',
    'FCO': 'Rome',
    'DCF': 'Roseau',
    'RUN': 'Saint-Denis',
    'ANU': 'Saint John\'s',
    'GCI': 'Saint Peter Port',
    'FSP': 'Saint-Pierre',
    'SPN': 'Saipan',
    'SJO': 'San Jose',
    'SJU': 'San Juan',
    'SAI': 'San Marino',
    'SAL': 'San Salvador',
    'SAH': 'Sana\'a',
    'SCL': 'Santiago',
    'SDQ': 'Santo Domingo',
    'TMS': 'Sao Tome',
    'SJJ': 'Sarajevo',
    'SEL': 'Seoul',
    'SIN': 'Singapore',
    'SKP': 'Skopje',
    'SOF': 'Sofia',
    'ARN': 'Stockholm',
    'SRE': 'Sucre',
    'SUV': 'Suva',
    'TPE': 'Taipei',
    'TLL': 'Tallinn',
    'TRW': 'Tarawa',
    'TAS': 'Tashkent',
    'TBS': 'Tbilisi',
    'TGU': 'Tegucigalpa',
    'IKA': 'Tehran',
    'PBH': 'Thimphu',
    'TIA': 'Tirana',
    'HND': 'Tokyo',
    'TIP': 'Tripoli',
    'TUN': 'Tunis',
    'ULN': 'Ulaanbaatar',
    'QKL': 'Vaduz',
    'MLA': 'Valletta',
    'VAT': 'Vatican City',
    'SEZ': 'Victoria',
    'VIE': 'Vienna',
    'VTE': 'Vientiane',
    'VNO': 'Vilnius',
    'WAW': 'Warsaw',
    'IAD': 'Washington D.C.',
    'WLG': 'Wellington',
    'WDH': 'Windhoek',
    'ASK': 'Yamoussoukro',
    'NSI': 'Yaounde',
    'EVN': 'Yerevan',
    'ZAG': 'Zagreb'
}, 
{
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, The Democratic Republic of The",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D'ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea, Democratic People's Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People's Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia, The Former Yugoslav Republic of",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States of",
    "MD": "Moldova, Republic of",
    "MC": "Monaco",
    "MN": "Mongolia",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and The Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "CS": "Serbia and Montenegro",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and The South Sandwich Islands",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan, Province of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic of",
    "TH": "Thailand",
    "TL": "Timor-leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Viet Nam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis and Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}]


