def city_codes():
    return [ {
    "AUH": "Abu Dhabi, United Arab Emirates",
    "ABV": "Abuja, Nigeria",
    "ACC": "Accra, Ghana",
    "ADL": "Adelaide, Australia",
    "ALG": "Algiers, Algeria",
    "AMM": "Amman, Jordan",
    "AMS": "Amsterdam, Netherlands",
    "ESB": "Ankara, Turkey",
    "APW": "Apia, Samoa",
    "ASB": "Ashgabat, Turkmenistan",
    "ASM": "Asmara, Eritrea",
    "TSE": "Astana, Kazakhstan",
    "ASU": "Asuncion, Paraguay",
    "ATH": "Athens, Greece",
    "ATL": "Atlanta, United States",
    "AKL": "Auckland, New Zealand",
    "BGW": "Baghdad, Iraq",
    "GYD": "Baku, Azerbaijan",
    "BKO": "Bamako, Mali",
    "BKK": "Bangkok, Thailand",
    "BLR": "Bangalore, India",
    "BGF": "Bangui, Central African Republic",
    "BJL": "Banjul, Gambia",
    "SKB": "Basseterre, Saint Kitts and Nevis",
    "PEK": "Beijing, China",
    "BEY": "Beirut, Lebanon",
    "BEG": "Belgrade, Serbia",
    "BZE": "Belmopan, Belize",
    "BER": "Berlin, Germany",
    "BRN": "Bern, Switzerland",
    "FRU": "Bishkek, Kyrgyzstan",
    "OXB": "Bissau, Guinea-Bissau",
    "BOG": "Bogota, Colombia",
    "BOS": "Boston, United States",
    "BSB": "Brasilia, Brazil",
    "BTS": "Bratislava, Slovakia",
    "BZV": "Brazzaville, Republic of the Congo",
    "BGI": "Bridgetown, Barbados",
    "BNE": "Brisbane, Australia",
    "BRU": "Brussels, Belgium",
    "OTP": "Bucharest, Romania",
    "BUD": "Budapest, Hungary",
    "EZE": "Buenos Aires, Argentina",
    "BJM": "Bujumbura, Burundi",
    "CAI": "Cairo, Egypt",
    "YYC": "Calgary, Canada",
    "CBR": "Canberra, Australia",
    "CPT": "Cape Town, South Africa",
    "CCS": "Caracas, Venezuela",
    "CWL": "Cardiff, United Kingdom",
    "SLU": "Castries, Saint Lucia",
    "CAY": "Cayenne, French Guiana",
    "GCM": "George Town, Cayman Islands",
    "CSX": "Changsha, China",
    "TFU": "Chengdu, China",
    "KIV": "Chisinau, Moldova",
    "CHC": "Christchurch, New Zealand",
    "CVG": "Cincinnati/Northern Kentucky, United States",
    "CPH": "Copenhagen, Denmark",
    "DKR": "Dakar, Senegal",
    "DFW": "Dallas/Fort Worth, United States",
    "DAM": "Damascus, Syria",
    "DMM": "Dammam, Saudi Arabia",
    "DAR": "Dar es Salaam, Tanzania",
    "DEL": "Delhi, India",
    "DEN": "Denver, United States",
    "DAC": "Dhaka, Bangladesh",
    "DIL": "Dili, Timor-Leste",
    "JIB": "Djibouti, Djibouti",
    "DOD": "Dodoma, Tanzania",
    "DOH": "Doha, Qatar",
    "IOM": "Douglas, Isle of Man",
    "DXB": "Dubai, United Arab Emirates",
    "DUB": "Dublin, Ireland",
    "DUS": "Dusseldorf, Germany",
    "DUR": "Durban, South Africa",
    "EDI": "Edinburgh, United Kingdom",
    "FNA": "Freetown, Sierra Leone",
    "FUN": "Funafuti, Tuvalu",
    "GBE": "Gaborone, Botswana",
    "GIB": "Gibraltar, Gibraltar",
    "OOL": "Gold Coast, Australia",
    "CAN": "Guangzhou, China",
    "GUM": "Hagatna, Guam",
    "HAK": "Haikou, China",
    "HAM": "Hamburg, Germany",
    "HAN": "Hanoi, Vietnam",
    "HRE": "Harare, Zimbabwe",
    "HAV": "Havana, Cuba",
    "HEL": "Helsinki, Finland",
    "HIR": "Honiara, Solomon Islands",
    "HKG": "Hong Kong, Hong Kong",
    "IAH": "Houston, United States",
    "HOU": "Houston, United States",
    "HYD": "Hyderabad, India",
    "ISB": "Islamabad, Pakistan",
    "CGK": "Jakarta, Indonesia",
    "JED": "Jeddah, Saudi Arabia",
    "JRS": "Jerusalem, Israel",
    "JNB": "Johannesburg, South Africa",
    "KBL": "Kabul, Afghanistan",
    "EBB": "Kampala, Uganda",
    "KIX": "Kansai, Japan",
    "KTM": "Kathmandu, Nepal",
    "KEF": "Keflavik, Iceland",
    "KRT": "Khartoum, Sudan",
    "IEV": "Kiev, Ukraine",
    "KGL": "Kigali, Rwanda",
    "KIN": "Kingston, Jamaica",
    "SVD": "Kingstown, Saint Vincent and the Grenadines",
    "FIH": "Kinshasa, Democratic Republic of the Congo",
    "KUL": "Kuala Lumpur, Malaysia",
    "KWI": "Kuwait City, Kuwait",
    "LPB": "La Paz, Bolivia",
    "LBV": "Libreville, Gabon",
    "LLW": "Lilongwe, Malawi",
    "LIM": "Lima, Peru",
    "LIS": "Lisbon, Portugal",
    "LJU": "Ljubljana, Slovenia",
    "LFW": "Lome, Togo",
    "LCY": "London, United Kingdom",
    "LGW": "London, United Kingdom",
    "LHR": "London, United Kingdom",
    "LAD": "Luanda, Angola",
    "LUN": "Lusaka, Zambia",
    "LUX": "Luxembourg City, Luxembourg",
    "MAD": "Madrid, Spain",
    "MAJ": "Majuro, Marshall Islands",
    "SSG": "Malabo, Equatorial Guinea",
    "MLE": "Malé, Maldives",
    "MLA": "Malta, Malta",
    "MGA": "Managua, Nicaragua",
    "BAH": "Manama, Bahrain",
    "MNL": "Manila, Philippines",
    "MPM": "Maputo, Mozambique",
    "MSU": "Maseru, Lesotho",
    "MBD": "Mbabane, Eswatini",
    "ROR": "Melekeok, Palau",
    "MEL": "Melbourne, Australia",
    "MEX": "Mexico City, Mexico",
    "MIA": "Miami, United States",
    "MXP": "Milan, Italy",
    "MSP": "Minneapolis, United States",
    "MSQ": "Minsk, Belarus",
    "MGQ": "Mogadishu, Somalia",
    "MCO": "Orlando, United States",
    "MCM": "Monaco, Monaco",
    "ROB": "Monrovia, Liberia",
    "MVD": "Montevideo, Uruguay",
    "YUL": "Montreal, Canada",
    "HAH": "Moroni, Comoros",
    "SVO": "Moscow, Russia",
    "BOM": "Mumbai, India",
    "MCT": "Muscat, Oman",
    "NBO": "Nairobi, Kenya",
    "NAS": "Nassau, Bahamas",
    "NPT": "Naypyidaw, Myanmar",
    "NIC": "Nicosia, Cyprus",
    "NKC": "Nouakchott, Mauritania",
    "TBU": "Nuku'alofa, Tonga",
    "GOH": "Nuuk, Greenland",
    "OUA": "Ouagadougou, Burkina Faso",
    "AUA": "Oranjestad, Aruba",
    "ITM": "Osaka, Japan",
    "OSL": "Oslo, Norway",
    "YOW": "Ottawa, Canada",
    "PMI": "Palma de Mallorca, Spain",
    "PTY": "Panama City, Panama",
    "PBM": "Paramaribo, Suriname",
    "CDG": "Paris, France",
    "ORY": "Paris, France",
    "PER": "Perth, Australia",
    "SXM": "Philipsburg, Sint Maarten",
    "PHX": "Phoenix, United States",
    "TGD": "Podgorica, Montenegro",
    "MRU": "Port Louis, Mauritius",
    "POM": "Port Moresby, Papua New Guinea",
    "VLI": "Port Vila, Vanuatu",
    "PAP": "Port-au-Prince, Haiti",
    "POS": "Port of Spain, Trinidad and Tobago",
    "OPO": "Porto, Portugal",
    "RAI": "Praia, Cape Verde",
    "PTA": "Pretoria, South Africa",
    "FNJ": "Pyongyang, North Korea",
    "UIO": "Quito, Ecuador",
    "RBA": "Rabat, Morocco",
    "RAM": "Ramallah, Palestine",
    "RIX": "Riga, Latvia",
    "RUH": "Riyadh, Saudi Arabia",
    "FCO": "Rome, Italy",
    "DOM": "Roseau, Dominica",
    "ANU": "Saint John's, Antigua and Barbuda",
    "GCI": "Saint Peter Port, Guernsey",
    "FSP": "Saint-Pierre, Saint Pierre and Miquelon",
    "RUN": "Saint-Denis, Réunion",
    "SPN": "Saipan, Northern Mariana Islands",
    "SFO": "San Francisco, United States",
    "SJO": "San Jose, Costa Rica",
    "SJU": "San Juan, Puerto Rico",
    "SMR": "San Marino, San Marino",
    "SAL": "San Salvador, El Salvador",
    "SAH": "Sana'a, Yemen",
    "SCL": "Santiago, Chile",
    "SDQ": "Santo Domingo, Dominican Republic",
    "TMS": "Sao Tome, Sao Tome and Principe",
    "SJJ": "Sarajevo, Bosnia and Herzegovina",
    "SEA": "Seattle-Tacoma, United States",
    "GMP": "Seoul, South Korea",
    "ICN": "Seoul, South Korea",
    "SHA": "Shanghai, China",
    "SZX": "Shenzhen, China",
    "SIN": "Singapore, Singapore",
    "SKP": "Skopje, North Macedonia",
    "SOF": "Sofia, Bulgaria",
    "ARN": "Stockholm, Sweden",
    "VST": "Stockholm, Sweden",
    "SRE": "Sucre, Bolivia",
    "SUV": "Suva, Fiji",
    "SYD": "Sydney, Australia",
    "PPT": "Tahiti, French Polynesia",
    "TPE": "Taipei, Taiwan",
    "TLL": "Tallinn, Estonia",
    "TAS": "Tashkent, Uzbekistan",
    "TRW": "Tarawa, Kiribati",
    "TBS": "Tbilisi, Georgia",
    "TGU": "Tegucigalpa, Honduras",
    "IKA": "Tehran, Iran",
    "TLV": "Tel Aviv, Israel",
    "PBH": "Thimphu, Bhutan",
    "TIA": "Tirana, Albania",
    "HND": "Tokyo, Japan",
    "NRT": "Tokyo, Japan",
    "YYZ": "Toronto, Canada",
    "TIP": "Tripoli, Libya",
    "TUN": "Tunis, Tunisia",
    "ULN": "Ulaanbaatar, Mongolia",
    "QJZ": "Vaduz, Liechtenstein",
    "MLA": "Valletta, Malta",
    "YVR": "Vancouver, Canada",
    "VAT": "Vatican City, Vatican City",
    "VIE": "Vienna, Austria",
    "VTE": "Vientiane, Laos",
    "VNO": "Vilnius, Lithuania",
    "WAW": "Warsaw, Poland",
    "IAD": "Washington, United States",
    "WLG": "Wellington, New Zealand",
    "WDH": "Windhoek, Namibia",
    "NSI": "Yaounde, Cameroon",
    "EVN": "Yerevan, Armenia",
    "ZAG": "Zagreb, Croatia",
    "ZRH": "Zurich, Switzerland"
}

, 
{
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Korea": "KP",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}
]


