def embed_codes():
    return {
        "Tirana, Albania": "https://widget.budgetyourtrip.com/location-widget-js/3183875",
        "Buenos Aires, Argentina": "https://widget.budgetyourtrip.com/location-widget-js/3435910",
        "Canberra, Australia": "https://widget.budgetyourtrip.com/location-widget-js/2172517",
        "Vienna, Austria": "https://widget.budgetyourtrip.com/location-widget-js/2761369",
        "Baku, Azerbaijan": "https://widget.budgetyourtrip.com/location-widget-js/587084",
        "Nassau, Bahamas": "https://widget.budgetyourtrip.com/location-widget-js/3571824",
        "Manama, Bahrain": "https://widget.budgetyourtrip.com/location-widget-js/290340",
        "Dhaka, Bangladesh": "https://widget.budgetyourtrip.com/location-widget-js/1185241",
        "Bridgetown, Barbados": "https://widget.budgetyourtrip.com/location-widget-js/3374036",
        "Minsk, Belarus": "https://widget.budgetyourtrip.com/location-widget-js/625144",
        "Brussels, Belgium": "https://widget.budgetyourtrip.com/location-widget-js/2800866",
        "Thimphu, Bhutan": "https://widget.budgetyourtrip.com/location-widget-js/1252416",
        "Sucre, Bolivia": "https://widget.budgetyourtrip.com/location-widget-js/3903987",
        "Sarajevo, Bosnia and Herzegovina": "https://widget.budgetyourtrip.com/location-widget-js/3191281",
        "Gaborone, Botswana": "https://widget.budgetyourtrip.com/location-widget-js/933773",
        "Brasilia, Brazil": "https://widget.budgetyourtrip.com/location-widget-js/3469058",
        "Sofia, Bulgaria": "https://widget.budgetyourtrip.com/location-widget-js/727011",
        "Ouagadougou, Burkina Faso": "https://widget.budgetyourtrip.com/location-widget-js/2357048",
        "Phnom Penh, Cambodia": "https://widget.budgetyourtrip.com/location-widget-js/1821306",
        "Ottawa, Canada": "https://widget.budgetyourtrip.com/location-widget-js/6094817",
        "Praia, Cape Verde": "https://widget.budgetyourtrip.com/location-widget-js/CV",
        "Santiago, Chile": "https://widget.budgetyourtrip.com/location-widget-js/3871336",
        "Beijing, China": "https://widget.budgetyourtrip.com/location-widget-js/1816670",
        "Bogota, Colombia": "https://widget.budgetyourtrip.com/location-widget-js/3688689",
        "San Jose, Costa Rica": "https://widget.budgetyourtrip.com/location-widget-js/3621841",
        "Zagreb, Croatia": "https://widget.budgetyourtrip.com/location-widget-js/3186886",
        "Havana, Cuba": "https://widget.budgetyourtrip.com/location-widget-js/3553478",
        "Nicosia, Cyprus": "https://widget.budgetyourtrip.com/location-widget-js/146268",
        "Prague, Czech Republic": "https://widget.budgetyourtrip.com/location-widget-js/3067696",
        "Copenhagen, Denmark": "https://widget.budgetyourtrip.com/location-widget-js/2618425",
        "Roseau, Dominica": "https://widget.budgetyourtrip.com/location-widget-js/3575635",
        "Santo Domingo, Dominican Republic": "https://widget.budgetyourtrip.com/location-widget-js/3492908",
        "Quito, Ecuador": "https://widget.budgetyourtrip.com/location-widget-js/3652462",
        "Cairo, Egypt": "https://widget.budgetyourtrip.com/location-widget-js/360630",
        "San Salvador, El Salvador": "https://widget.budgetyourtrip.com/location-widget-js/3583361",
        "London, England": "https://widget.budgetyourtrip.com/location-widget-js/2643743",
        "Tallinn, Estonia": "https://widget.budgetyourtrip.com/location-widget-js/588409",
        "Mbabane, Eswatini": "https://widget.budgetyourtrip.com/location-widget-js/934985",
        "Addis Ababa, Ethiopia": "https://widget.budgetyourtrip.com/location-widget-js/344979",
        "Suva, Fiji": "https://widget.budgetyourtrip.com/location-widget-js/2198148",
        "Helsinki, Finland": "https://widget.budgetyourtrip.com/location-widget-js/658225",
        "Paris, France": "https://widget.budgetyourtrip.com/location-widget-js/2988507",
        "Tbilisi, Georgia": "https://widget.budgetyourtrip.com/location-widget-js/611717",
        "Berlin, Germany": "https://widget.budgetyourtrip.com/location-widget-js/2950159",
        "Accra, Ghana": "https://widget.budgetyourtrip.com/location-widget-js/2306104",
        "Athens, Greece": "https://widget.budgetyourtrip.com/location-widget-js/264371",
        "Saint George's, Grenada": "https://widget.budgetyourtrip.com/location-widget-js/3579925",
        "Guatemala City, Guatemala": "https://widget.budgetyourtrip.com/location-widget-js/3598132",
        "Port au Prince, Haiti": "https://widget.budgetyourtrip.com/location-widget-js/3718426",
        "Budapest, Hungary": "https://widget.budgetyourtrip.com/location-widget-js/3054643",
        "Reykjavik, Iceland": "https://widget.budgetyourtrip.com/location-widget-js/3413829",
        "New Delhi, India": "https://widget.budgetyourtrip.com/location-widget-js/1261481",
        "Jakarta, Indonesia": "https://widget.budgetyourtrip.com/location-widget-js/1642911",
        "Tehran, Iran": "https://widget.budgetyourtrip.com/location-widget-js/112931",
        "Baghdad, Iraq": "https://widget.budgetyourtrip.com/location-widget-js/98182",
        "Dublin, Ireland": "https://widget.budgetyourtrip.com/location-widget-js/2964574",
        "Jerusalem, Israel": "https://widget.budgetyourtrip.com/location-widget-js/281184",
        "Rome, Italy": "https://widget.budgetyourtrip.com/location-widget-js/3169070",
        "Kingston, Jamaica": "https://widget.budgetyourtrip.com/location-widget-js/3489854",
        "Tokyo, Japan": "https://widget.budgetyourtrip.com/location-widget-js/1850147",
        "Amman, Jordan": "https://widget.budgetyourtrip.com/location-widget-js/250441",
        "Astana, Kazakhstan": "https://widget.budgetyourtrip.com/location-widget-js/1526273",
        "Nairobi, Kenya": "https://widget.budgetyourtrip.com/location-widget-js/184745",
        "Bishkek, Kyrgyzstan": "https://widget.budgetyourtrip.com/location-widget-js/1528675",
        "Vientiane, Laos": "https://widget.budgetyourtrip.com/location-widget-js/1651944",
        "Riga, Latvia": "https://widget.budgetyourtrip.com/location-widget-js/456172",
        "Beirut, Lebanon": "https://widget.budgetyourtrip.com/location-widget-js/276781",
        "Maseru, Lesotho": "https://widget.budgetyourtrip.com/location-widget-js/932505",
        "Monrovia, Liberia": "https://widget.budgetyourtrip.com/location-widget-js/2274895",
        "Tripoli, Libya": "https://widget.budgetyourtrip.com/location-widget-js/2210247",
        "Vaduz, Liechtenstein": "https://widget.budgetyourtrip.com/location-widget-js/3042030",
        "Vilnius, Lithuania": "https://widget.budgetyourtrip.com/location-widget-js/593116",
        "Luxembourg, Luxembourg": "https://widget.budgetyourtrip.com/location-widget-js/2960316",
        "Antananarivo, Madagascar": "https://widget.budgetyourtrip.com/location-widget-js/1070940",
        "Lilongwe, Malawi": "https://widget.budgetyourtrip.com/location-widget-js/927967",
        "Kuala Lumpur, Malaysia": "https://widget.budgetyourtrip.com/location-widget-js/1735161",
        "Male, Maldives": "https://widget.budgetyourtrip.com/location-widget-js/1282027",
        "Bamako, Mali": "https://widget.budgetyourtrip.com/location-widget-js/2460596",
        "Valletta, Malta": "https://widget.budgetyourtrip.com/location-widget-js/2562305",
        "Majuro, Marshall Islands": "https://widget.budgetyourtrip.com/location-widget-js/2113779",
        "Nouakchott, Mauritania": "https://widget.budgetyourtrip.com/location-widget-js/2377450",
        "Port Louis, Mauritius": "https://widget.budgetyourtrip.com/location-widget-js/1558435",
        "Mexico City, Mexico": "https://widget.budgetyourtrip.com/location-widget-js/3530597",
        "Palikir, Micronesia": "https://widget.budgetyourtrip.com/location-widget-js/2081986",
        "Chisinau, Moldova": "https://widget.budgetyourtrip.com/location-widget-js/618426",
        "Monaco, Monaco": "https://widget.budgetyourtrip.com/location-widget-js/2993457",
        "Ulaanbaatar, Mongolia": "https://widget.budgetyourtrip.com/location-widget-js/2028462",
        "Podgorica, Montenegro": "https://widget.budgetyourtrip.com/location-widget-js/3193044",
        "Rabat, Morocco": "https://widget.budgetyourtrip.com/location-widget-js/2538474",
        "Maputo, Mozambique": "https://widget.budgetyourtrip.com/location-widget-js/1036973",
        "Windhoek, Namibia": "https://widget.budgetyourtrip.com/location-widget-js/3352136",
        "Yaren, Nauru": "https://widget.budgetyourtrip.com/location-widget-js/2110425",
        "Kathmandu, Nepal": "https://widget.budgetyourtrip.com/location-widget-js/1283240",
        "Amsterdam, Netherlands": "https://widget.budgetyourtrip.com/location-widget-js/2759794",
        "Wellington, New Zealand": "https://widget.budgetyourtrip.com/location-widget-js/2179537",
        "Managua, Nicaragua": "https://widget.budgetyourtrip.com/location-widget-js/3617763",
        "Niamey, Niger": "https://widget.budgetyourtrip.com/location-widget-js/2440485",
        "Abuja, Nigeria": "https://widget.budgetyourtrip.com/location-widget-js/2352778",
        "Oslo, Norway": "https://widget.budgetyourtrip.com/location-widget-js/3143244",
        "Muscat, Oman": "https://widget.budgetyourtrip.com/location-widget-js/287286",
        "Islamabad, Pakistan": "https://widget.budgetyourtrip.com/location-widget-js/1176615",
        "Melekeok, Palau": "https://widget.budgetyourtrip.com/location-widget-js/7670923",
        "Panama City, Panama": "https://widget.budgetyourtrip.com/location-widget-js/3703443",
        "Port Moresby, Papua New Guinea": "https://widget.budgetyourtrip.com/location-widget-js/2088122",
        "Asuncion, Paraguay": "https://widget.budgetyourtrip.com/location-widget-js/3439389",
        "Lima, Peru": "https://widget.budgetyourtrip.com/location-widget-js/3936456",
        "Manila, Philippines": "https://widget.budgetyourtrip.com/location-widget-js/1701668",
        "Warsaw, Poland": "https://widget.budgetyourtrip.com/location-widget-js/756135",
        "Lisbon, Portugal": "https://widget.budgetyourtrip.com/location-widget-js/2267057",
        "Doha, Qatar": "https://widget.budgetyourtrip.com/location-widget-js/290030",
        "Bucharest, Romania": "https://widget.budgetyourtrip.com/location-widget-js/683506",
        "Moscow, Russia": "https://widget.budgetyourtrip.com/location-widget-js/524901",
        "Kigali, Rwanda": "https://widget.budgetyourtrip.com/location-widget-js/202061",
        "Basseterre, Saint Kitts and Nevis": "https://widget.budgetyourtrip.com/location-widget-js/3575551",
        "Castries, Saint Lucia": "https://widget.budgetyourtrip.com/location-widget-js/3576812",
        "Kingstown, Saint Vincent and the Grenadines": "https://widget.budgetyourtrip.com/location-widget-js/3577887",
        "Apia, Samoa": "https://widget.budgetyourtrip.com/location-widget-js/4035413",
        "San Marino, San Marino": "https://widget.budgetyourtrip.com/location-widget-js/3168068",
        "Sao Tome, Sao Tome and Principe": "https://widget.budgetyourtrip.com/location-widget-js/2410763",
        "Riyadh, Saudi Arabia": "https://widget.budgetyourtrip.com/location-widget-js/108410",
        "Dakar, Senegal": "https://widget.budgetyourtrip.com/location-widget-js/2253354",
        "Belgrade, Serbia": "https://widget.budgetyourtrip.com/location-widget-js/792680",
        "Victoria, Seychelles": "https://widget.budgetyourtrip.com/location-widget-js/241131",
        "Freetown, Sierra Leone": "https://widget.budgetyourtrip.com/location-widget-js/2403846",
        "Singapore, Singapore": "https://widget.budgetyourtrip.com/location-widget-js/1880252",
        "Bratislava, Slovakia": "https://widget.budgetyourtrip.com/location-widget-js/3060972",
        "Ljubljana, Slovenia": "https://widget.budgetyourtrip.com/location-widget-js/3196359",
        "Honiara, Solomon Islands": "https://widget.budgetyourtrip.com/location-widget-js/2108502",
        "Mogadishu, Somalia": "https://widget.budgetyourtrip.com/location-widget-js/53654",
        "Pretoria, South Africa": "https://widget.budgetyourtrip.com/location-widget-js/964137",
        "Seoul, South Korea": "https://widget.budgetyourtrip.com/location-widget-js/1835848",
        "Juba, South Sudan": "https://widget.budgetyourtrip.com/location-widget-js/372469",
        "Madrid, Spain": "https://widget.budgetyourtrip.com/location-widget-js/3117735",
        "Colombo, Sri Lanka": "https://widget.budgetyourtrip.com/location-widget-js/1248991",
        "Khartoum, Sudan": "https://widget.budgetyourtrip.com/location-widget-js/379252",
        "Paramaribo, Suriname": "https://widget.budgetyourtrip.com/location-widget-js/3383330",
        "Stockholm, Sweden": "https://widget.budgetyourtrip.com/location-widget-js/2673730",
        "Bern, Switzerland": "https://widget.budgetyourtrip.com/location-widget-js/2661552",
        "Damascus, Syria": "https://widget.budgetyourtrip.com/location-widget-js/170654",
        "Taipei, Taiwan": "https://widget.budgetyourtrip.com/location-widget-js/1668341",
        "Dushanbe, Tajikistan": "https://widget.budgetyourtrip.com/location-widget-js/1221874",
        "Dodoma, Tanzania": "https://widget.budgetyourtrip.com/location-widget-js/TZ",
        "Bangkok, Thailand": "https://widget.budgetyourtrip.com/location-widget-js/1609350",
        "Lome, Togo": "https://widget.budgetyourtrip.com/location-widget-js/2365267",
        "Nuku'alofa, Tonga": "https://widget.budgetyourtrip.com/location-widget-js/4032402",
        "Port of Spain, Trinidad and Tobago": "https://widget.budgetyourtrip.com/location-widget-js/3573890",
        "Tunis, Tunisia": "https://widget.budgetyourtrip.com/location-widget-js/2464470",
        "Ankara, Turkey": "https://widget.budgetyourtrip.com/location-widget-js/323786",
        "Ashgabat, Turkmenistan": "https://widget.budgetyourtrip.com/location-widget-js/162183",
        "Funafuti, Tuvalu": "https://widget.budgetyourtrip.com/location-widget-js/2110425",
        "Kampala, Uganda": "https://widget.budgetyourtrip.com/location-widget-js/232422",
        "Kyiv, Ukraine": "https://widget.budgetyourtrip.com/location-widget-js/703448",
        "Abu Dhabi, United Arab Emirates": "https://widget.budgetyourtrip.com/location-widget-js/292968",
        "London, United Kingdom": "https://widget.budgetyourtrip.com/location-widget-js/2643743",
        "Washington D.C., United States": "https://widget.budgetyourtrip.com/location-widget-js/4140963",
        "Montevideo, Uruguay": "https://widget.budgetyourtrip.com/location-widget-js/3441575",
        "Tashkent, Uzbekistan": "https://widget.budgetyourtrip.com/location-widget-js/1512569",
        "Port Vila, Vanuatu": "https://widget.budgetyourtrip.com/location-widget-js/2135171",
        "Vatican City, Vatican City": "https://widget.budgetyourtrip.com/location-widget-js/6691831",
        "Caracas, Venezuela": "https://widget.budgetyourtrip.com/location-widget-js/3646738",
        "Hanoi, Vietnam": "https://widget.budgetyourtrip.com/location-widget-js/1581130",
        "Sanaa, Yemen": "https://widget.budgetyourtrip.com/location-widget-js/69559",
        "Lusaka, Zambia": "https://widget.budgetyourtrip.com/location-widget-js/909137",
        "Harare, Zimbabwe": "https://widget.budgetyourtrip.com/location-widget-js/890299"
}